# Generated by Django 4.0 on 2021-12-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='anime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='nick',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
