# Generated by Django 4.0 on 2021-12-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_post_anime_rename_text_post_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nick',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='anime',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
